### ISSUE TITLE
what is "class_dict.npy" and "class_dict_inv.npy"?

### ISSUE THREAD

**Issue by xunfeng2zkj** [The-Learning-And-Vision-Atelier-LAVA/PoSFeat#1]
![image](https://user-images.githubusercontent.com/22878414/164203581-4958eb85-5990-4eaf-83e8-fff1079b68b2.png)

**Comment by KunB-Fighting** [comment]
I am sorry, this dictionary is actually not used, you can comment out that line and related lines in the dataset file.

**Comment by KunB-Fighting** [comment]
The redundant codes have been removed, you can synchronize the codes now.
