### ISSUE TITLE
error on running train.py

### ISSUE THREAD

**Issue by atharvjairath** [The-Learning-And-Vision-Atelier-LAVA/PoSFeat#10]
@KunB-Fighting 
I fixed the issue in #4  by using `kp1_comb = (int(kp1[0]+w+mid_pad), int(kp1[1]))` instead of kp1 in trainer.py

After doing that, the above error was fixed but it gave me a new following error:
```
line 1225, in _process_data
    data.reraise()
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/private/atharv/hyperturing/posfeat/PoSFeat/managers/trainer.py", line 151, in my_collate
    return torch.utils.data.dataloader.default_collate(batch)
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 45, in default_collate
    elem = batch[0]
IndexError: list index out of range
```

not sure why batch[0] is out of index

**Comment by KunB-Fighting** [comment]
Maybe your batch size is too small. You can find that  the dataset may return None if the samples do not meet requirements, such as when the rotation is too large. And you can resample another index when the current sample does not meet requirements. Or you can simply comment out these checks, but this may lead to performance drop

**Comment by KunB-Fighting** [comment]
The collate_fn is used to get rid of the None samples, and when your batch size is too small (for example 1 or 2), it is possible that all samples are None, and this will leads to "batch[0] is out of index"

**Comment by atharvjairath** [comment]
Yes, my batch size is 2, this must be causing the issue. will Increasing the batch size fix the issue?

**Comment by KunB-Fighting** [comment]
Yes, the batch size 6 or 8 will hardly meet this issue. If your GPU can not suppose a larger batch size, I suggest you modify the code to resample another index and freeze bn during training (small bs will lead to performance drop when there is bn in net)

> Yes, my batch size is 2, this must be causing the issue. will Increasing the batch size fix the issue?

**Comment by atharvjairath** [comment]
Since, I cant load batch size higher than 4, Multi-gpu is the way to go,
but as I ran `python train.py --config ./configs/train_desc.yaml --local_rank 0`

this gave me an error,
```
./ckpts/descriptor
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    trainer = Trainer(args)
  File "/mnt/private/atharv/hyperturing/posfeat/PoSFeat/managers/trainer.py", line 68, in __init__
    self.set_device()
  File "/mnt/private/atharv/hyperturing/posfeat/PoSFeat/managers/trainer.py", line 168, in set_device
    dist.init_process_group(backend='nccl') 
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 166, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```

how can I fix this? @KunB-Fighting 
Thanks in advance!

**Comment by KunB-Fighting** [comment]
the local_rank should not be assigned by yourself, this is used by torch.distributed, and I recommend this tutorial on pytorch website: [https://pytorch.org/tutorials/intermediate/ddp_tutorial.html](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html). But we find that the DDP is slow, so maybe you should modify the code to use dataparallel API in pytorch.

**Comment by KunB-Fighting** [comment]
As we mentioned in README, current codes use DDP API to achieve multi GPU training, but it is slow (and I don't know why QAQ). I think it is better to use DP API.

**Comment by KunB-Fighting** [comment]
> Yes, my batch size is 2, this must be causing the issue. will Increasing the batch size fix the issue?

Hi, now we update the dataset code, so that when the data dose not meet requirements, it would sample another one instead of returning None.

**Comment by atharvjairath** [comment]
@KunB-Fighting That's great, That will work. Will look into the DDP and DD apis to see if I can fix the code.

**Comment by atharvjairath** [comment]
@KunB-Fighting 
For Training description net should we use `data: 'MegaDepth_SIFT' `  in train_desc.yaml
or any other data class since you made changes in `MegaDepth_superpoint`?

Also please confirm the same for detection net.

**Comment by atharvjairath** [comment]
Made the changes in MegaDepth_SIFT dataset class and it is working now.

**Comment by KunB-Fighting** [comment]
Oh, I'm sorry I made the update incorrectly. It should make the same update for MegaDepth_SIFT .  I will correct it tomorrow.
