### ISSUE TITLE
关于detector网络的问题

### ISSUE THREAD

**Issue by FlyFish-space** [The-Learning-And-Vision-Atelier-LAVA/PoSFeat#11]
请问为什么PosFeat的detector网络输入的是图像+fine特征图。而且在计算过程中计算相邻点的SSIM，最后在与对应的图像/特征图相乘，这样的目的是什么？可否理解为一种positional encoding，引入位置信息？谢谢！

**Comment by KunB-Fighting** [comment]
detector的输入包括深层特征，浅层特征和图像，这是为了让detector感知到更多的细节信息。而SSIM和D2实际上是没有使用的，只是之前的实验代码（尝试引入一些先验），实际用的是identity，这些部分放出来也是希望说不定能为使用者提供一些帮助。

Q： why there is the image and the fine feature map in the detector's inputs. And why there is SSIM when generate key point map? Is it a way of position encoding?

A: the inputs of detector include the image, shallow feature and deep feature, and the shallow feature as well as image provides detail information for detectors.

For SSIM, it is actually not used, that is our test code. We had planned to provide some prior to the detector with SSIM/D2/ASL_Peak, but failed. Actually,  we the 'identity' function, which provides no prior.

**Comment by FlyFish-space** [comment]
THANKS!
