### ISSUE TITLE
[Question] Can PosFeat replace SuperPoint in SuperGlue paper?

### ISSUE THREAD

**Issue by atharvjairath** [The-Learning-And-Vision-Atelier-LAVA/PoSFeat#7]
Hey,
Great work with PoSFeat, I want to replace SuperPoint in SuperGlue with your model, is the possible and which part should I use of your model to replace it.

Also can you please provide the pretrained model.

Thanks! :)

**Comment by KunB-Fighting** [comment]
Thanks for your attention, the PoSFeat plays the same role as superpoint, so you can just replace the entire superpoint network with our description net and detection net. In fact, if you read the code of superglue, you can find that the input of superglue is the keypoints and descriptors, which means you should extract keypoints as well as the descriptors according to the keypoint score map and dense feature map, and you can refers to our extractor.py

**Comment by atharvjairath** [comment]
Thanks for clarifying!
